BackendBundle\Entity\AcademicProduction:
    type: entity
    table: academic_production
    indexes:
        id_user:
            columns:
                - id_user
    id:
        idAcademicProduction:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_academic_production
            generator:
                strategy: IDENTITY
    fields:
        typeAcademicProd:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: type_academic_prod
        nameAcademicProd:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
            column: name_academic_prod
        idUser:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: id_user
        date:
            type: date
            nullable: false
    lifecycleCallbacks: {  }
