BackendBundle\Entity\Modality:
    type: entity
    table: modality
    id:
        codMod:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: cod_mod
            generator:
                strategy: IDENTITY
    fields:
        nameMod:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: name_mod
    lifecycleCallbacks: {  }
