BackendBundle\Entity\ProducAcademic:
    type: entity
    table: produc_academic
    indexes:
        produc_academic_FKIndex1:
            columns:
                - cod_typepro
        produc_academic_FKIndex2:
            columns:
                - cod_usr
    id:
        codProdc:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: cod_prodc
            generator:
                strategy: IDENTITY
    fields:
        nameProduc:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: name_produc
        dateProduc:
            type: date
            nullable: false
            column: date_produc
        addressProduc:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: address_produc
        descripProduc:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: descrip_produc
        certificateProduc:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: certificate_produc
    manyToOne:
        codTypepro:
            targetEntity: TypeProduc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cod_typepro:
                    referencedColumnName: cod_typepro
            orphanRemoval: false
        codUsr:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cod_usr:
                    referencedColumnName: cod_usr
            orphanRemoval: false
    lifecycleCallbacks: {  }
