BackendBundle\Entity\Rol:
    type: entity
    table: rol
    id:
        idrol:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idRol
            generator:
                strategy: IDENTITY
    fields:
        namerol:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: nameRol
    lifecycleCallbacks: {  }
