BackendBundle\Entity\Title:
    type: entity
    table: titles
    indexes:
        titles_FKIndex1:
            columns:
                - cod_level
        titles_FKIndex2:
            columns:
                - cod_mod
        titles_FKIndex3:
            columns:
                - cod_usr
    id:
        codTitle:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: cod_title
            generator:
                strategy: IDENTITY
    fields:
        nameTitle:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: name_title
        dategradTitle:
            type: date
            nullable: false
            column: dategrad_title
    manyToOne:
        codLevel:
            targetEntity: LevelEduc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cod_level:
                    referencedColumnName: cod_level
            orphanRemoval: false
        codMod:
            targetEntity: Modality
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cod_mod:
                    referencedColumnName: cod_mod
            orphanRemoval: false
        codUsr:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cod_usr:
                    referencedColumnName: cod_usr
            orphanRemoval: false
    lifecycleCallbacks: {  }
