BackendBundle\Entity\TypeEvent:
    type: entity
    table: type_event
    id:
        idTypeEvent:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_type_event
            generator:
                strategy: IDENTITY
    fields:
        nameEvent:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: name_event
    lifecycleCallbacks: {  }
