BackendBundle\Entity\TypeAcademicProd:
    type: entity
    table: type_academic_prod
    id:
        idTypeAcademicProd:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_type_academic_prod
            generator:
                strategy: IDENTITY
    fields:
        nomTypeEvent:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: nom_type_event
    lifecycleCallbacks: {  }
