BackendBundle\Entity\User:
    type: entity
    table: user
    indexes:
        id_user:
            columns:
                - id_user
        rol:
            columns:
                - rol
    uniqueConstraints:
        id_user_2:
            columns:
                - id_user
    id:
        idIntUsr:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_int_usr
            generator:
                strategy: IDENTITY
    fields:
        password:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        idUser:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: id_user
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        lastname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        mail:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        rol:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
